server:
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
    #sql-script-encoding: UTF-8

  h2:
    console:
      #h2 console ????
      enabled: true
      settings:
        web-allow-others: true

      #path: /h2-console

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
        #ddl-auto: create
      properties:
        hibernate:
          #          show-sql: true
          format_sql: true
          default_batch_fetch_size: 100
      datasource-platform: org.hibernate.dialect.H2Dialect

  http:
    encoding:
      charset: UTF-8
      endable: true
      force: true

  #  resouces:
  #    static-locations: classpath:/resources/static/

  devtools:
    livereload:
      enabled: true